---
title: "Lizards Parameter Estimation (Task 2)"
author: "Lucas Boyd"
date: "2/1/2022"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# attach packages
library(tidyverse)
library(broom)
library(purrr)
library(here)
library(janitor)
library(kableExtra)
```


```{r}
# reading in the data
lizards <- read_csv(here("data", "lizard.csv")) %>% 
  clean_names() %>% 
  mutate(log_weight = log(weight)) %>% # log transforming the data - since we are using an exponential base equation
  mutate(log_length = log(sv_length)) %>% 
  drop_na()
```


```{r, include = FALSE}
# looking at the data 
ggplot(data = lizards, aes(x = sv_length, y = weight)) +
         geom_point()
# taking a quick peak at the log transformed data
ggplot(data = lizards, aes(x = log_length, y = log_weight)) +
         geom_point()
```
#### Starting model:
\[
W = a(SVL)^b
\]

```{r}
guess_model <- lm(log_weight ~ log_length, data = lizards)

tidy_guess <- tidy(guess_model)

coef <- coefficients(guess_model)
# estimate of coefficient b = 2.537 `r tidy_guess$estimate[2]`
# estmate of coefficent b = -8.475 `r tidy_guess$estimate[1]`

# storing a function of our model with coefficients
weight_function <- function(a, sv_length, b){
  weight = a*(sv_length)^b
  return(weight)
}
```

```{r}
# running the NLS
lizards_nls <- nls(weight ~ weight_function(a, sv_length, b),
                  data = lizards,
                  start = list(b = coef[2],
                               a = coef[1]),
                  trace = TRUE)

nls_tidy <- tidy(lizards_nls)

# making a table of the results of the NLS model
nls_tidy %>% 
  select(-statistic) %>% 
  mutate(p.value = case_when(
    p.value < 0.001 ~ "<0.001"
  )) %>% 
kable(col.names = c("Terms", "Coefficients", "Standard Error", "P.Value"),
      digits = 4) %>% 
  kable_minimal(full_width = FALSE)


```


```{r}
lizards_augment <- augment(lizards_nls)

ggplot() +
  geom_point(data = lizards, aes(
             x = sv_length,
             y = weight, 
             color = sex)) +
  geom_line(data = lizards_augment, aes(
            x = sv_length,
            y = .fitted), color = "black") +
  theme_minimal()
```
### Western Whiptails 
```{r}
whips <- lizards %>% 
  filter(spp == "CNTI", sex == "M") 

guess_whips <- lm(log_weight ~ log_length, data = whips)

tidy_whips_guess <- tidy(guess_model)

whips_coef <- coefficients(guess_whips)

whips_nls <- nls(weight ~ weight_function(a, sv_length, b),
                  data = whips,
                  start = list(b = whips_coef[2],
                               a = whips_coef[1]),
                  trace = TRUE)

whips_nls_tidy <- tidy(whips_nls)

whips_nls_tidy %>% 
  select(-statistic) %>% 
  mutate(p.value = case_when(
    p.value < 0.001 ~ "<0.001"
  )) %>% 
kable(col.names = c("Terms", "Coefficients", "Standard Error", "P.Value"),
      digits = 4) %>% 
  kable_minimal(full_width = FALSE)
```


```{r}
whips_augment <- augment(whips_nls)

ggplot() +
  geom_point(data = whips, aes(
             x = sv_length,
             y = weight)) +
  geom_line(data = whips_augment, aes(
            x = sv_length,
            y = .fitted), color = "red") +
  theme_minimal()
```
```

